name: Try Build App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          pull: true
          load: true
          push: false
          tags: srs-dev
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            BUILD_PROFILE=dev
      - name: Create json
        run: |
          echo '{"redirects": {"duck": "https://duckduckgo.com"}}' > redirects.json
      - name: Test
        shell: bash
        run: |
          set -euxo pipefail
          docker run --platform=linux/amd64 -d --rm -p 3000:3000 --name srs --mount type=bind,source="$(pwd)/redirects.json",target=/app/redirects.json --pull=never srs-dev
          sleep 15
          docker logs srs
          curl localhost:3000
          docker stop srs
