name: Build and push release

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

jobs:
  build-docker:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          tags: ghcr.io/harmless-tech/simple-redirect-service:latest,ghcr.io/harmless-tech/simple-redirect-service:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
      - name: Extract binary arm64
        run: docker run --rm --platform=linux/arm64 --mount type=bind,source=$(pwd),target=/pkg-repo --pull=always ghcr.io/harmless-tech/simple-redirect-service:${{ github.ref_name }} sh -c "cp /app/simple-redirect-service /pkg-repo"
      - name: Tar aarch64
        run: tar -czvf aarch64-unknown-linux-musl.tar.gz simple-redirect-service
      - name: Hash aarch64
        run: sha256sum aarch64-unknown-linux-musl.tar.gz >> aarch64-unknown-linux-musl.sha256
      - name: Extract binary amd64
        run: docker run --rm --platform=linux/amd64 --mount type=bind,source=$(pwd),target=/pkg-repo --pull=always ghcr.io/harmless-tech/simple-redirect-service:${{ github.ref_name }} sh -c "cp /app/simple-redirect-service /pkg-repo"
      - name: Tar x86_64
        run: tar -czvf x86_64-unknown-linux-musl.tar.gz simple-redirect-service
      - name: Hash x86_64
        run: sha256sum x86_64-unknown-linux-musl.tar.gz >> x86_64-unknown-linux-musl.sha256
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: unknown-linux-musl
          path: |
            aarch64-unknown-linux-musl.tar.gz
            aarch64-unknown-linux-musl.sha256
            x86_64-unknown-linux-musl.tar.gz
            x86_64-unknown-linux-musl.sha256
      - name: Release Artifact
        uses: svenstaro/upload-release-action@2.4.0
        with:
          tag: ${{ github.ref_name }}
          release_name: simple-redirect-service-${{ github.ref_name }}
          overwrite: true
          file_glob: true
          file: "*-unknown-linux-musl*"
