name: Build and push release

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

jobs:
  build-docker:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          tags: ghcr.io/harmless-tech/simple-redirect-service:latest,ghcr.io/harmless-tech/simple-redirect-service:${{ github.ref_name }},quay.io/harmless-tech/simple-redirect-service:latest,quay.io/harmless-tech/simple-redirect-service:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: simple-redirect-service-${{ github.ref_name }}
          makeLatest: true
          allowUpdates: true
